### ISSUE TITLE
Add a reloader controller to kubernetes deployment

### ISSUE THREAD

**Issue by moabu** [GluuFederation/cloud-native-edition#102]
We need to take advantage of initializing a rolling update if any gluu ConfigMap or secret is modified during a deployment.

**Comment by iromli** [comment]
@moabu did you mean re-deploying pods if any of config/secret updated?

**Comment by moabu** [comment]
yes I have tested a method and it is working . I hoping this will be in pygluu 1.04. This will be in the frontend @iromli.

**Comment by moabu** [comment]
In preparation for adding a reloader , configuration has been reduced to one file. We now have two ConfigMaps and one secret.
