### ISSUE TITLE
Replace builtins input with Click

### ISSUE THREAD

**Issue by iromli** [GluuFederation/cloud-native-edition#119]
The `pygluu/kubernetes/prompt` consists of lots of `input` calls. Many of them are dealing with default values, confirmation, validation, etc. Those are tedious tasks and error prone.
I would like to propose to replace them with [Click](https://click.palletsprojects.com).

**Comment by moabu** [comment]
We need to think this through a bit. The idea from start was to steer away from external libs and use STD library. But at this point we are likely moving into a container environment installer and this repo will be its source. I think its time for Click to walk in. We also should replace argparse since Click will be available.

**Comment by iromli** [comment]
> The idea from start was to steer away from external libs and use STD library

That wouldn't be possible from start as we relies heavily on kubernetes and YAML packages.

**Comment by moabu** [comment]
as much as possible. :D Anyways as said lets move on with adding It at this point because we will move into using a Kubernetes manifest to install.

**Comment by moabu** [comment]
change of prompts to Click will be replaced gradually . 
https://github.com/GluuFederation/cloud-native-edition/pull/125

**Comment by moabu** [comment]
https://github.com/GluuFederation/cloud-native-edition/pull/127

**Comment by moabu** [comment]
https://github.com/GluuFederation/cloud-native-edition/pull/130

**Comment by moabu** [comment]
https://github.com/GluuFederation/cloud-native-edition/pull/131

**Comment by moabu** [comment]
https://github.com/GluuFederation/cloud-native-edition/pull/132

**Comment by moabu** [comment]
https://github.com/GluuFederation/cloud-native-edition/commit/0d6bb380d84602f941d55510ca1306bbaf32d6ec

**Comment by iromli** [comment]
Most of `builtins.input` have been replaced by click. Closing this issue.
