### ISSUE TITLE
Add alternative to opt-out license and version in Prompt.__init__ method

### ISSUE THREAD

**Issue by iromli** [GluuFederation/cloud-native-edition#121]
Currently, creating `pygluu.kubernetes.prompt.Prompt` instance prompts for license and version thus halting the runtime.

```python
class Prompt:
    def __init__(self):
        # ... omitted
        self.prompt_license()
        self.prompt_version()
```

This behavior makes the unit testing for `Prompt` methods is more difficult as the `builtins.input` must be patched all the time.

Consider this snippet:

```python
from pygluu.kubernetes.prompt import Prompt


def test_prompt():
    prompter = Prompt()  # this will halt the code to wait for user-input
```

The `Prompt.prompt_license` and `Prompt.prompt_version` must be extracted from `Prompt.__init__` method, but it is not clear to me which part of the CLI (`pygluu/kubernetes.create`) that requires `Prompt.license` and/or `Prompt.version`.

**Comment by iromli** [comment]
As an alternative perhaps we can introduce flag in init method, i.e.

```python
class Prompt:    
    def __init__(self, accept_license=False, version=""):
        # ... omitted ...
        if not accept_license:
            self.prompt_license()

        if not version:
            self.prompt_version()
```

This approach will avoid having to call `prompt_license` and `prompt_version` explicitly, but we add a way to bypass the prompt (for testcases).

For CLI:

```python
from pygluu.kubernetes.prompt import Prompt

prompter = Prompt()
```

For testcases:

```python
from pygluu.kubernetes.prompt import Prompt

prompter = Prompt(accept_license=True, version="4.2.0_dev")
```

**Comment by moabu** [comment]
Yes. Adding to [Init](https://github.com/GluuFederation/cloud-native-edition/issues/121#issuecomment-646877216) to pass test cases will be better at this point.
