### ISSUE TITLE
Cannot access Gluu UI running on Minikube, no problem on MicroK8s

### ISSUE THREAD

**Issue by hhblnw** [GluuFederation/cloud-native-edition#136]
I installed Gluu on a Minikube instance, following the [instructions on gluu.org.](https://gluu.org/docs/gluu-server/installation-guide/install-kubernetes/#minikube) The install went through but I wasn't able to access the Gluu UI. There was no response on port 80, 443, 8000, 8080, 8443 or any of the other ports I tried. For the IP address, I used the IP of the VM Minikube was running on which in my case was 10.0.0.96. I also tried 172.17.0.2 from within the VM which is the internal Minikube IP.

None of this worked. In some cases, I got a 404, in others "connection refused". I tried playing with "kubectl port-forward", "minikube tunnel" and a bunch of other things but to no avail.

However, when I installed Gluu on a MicroK8s instance on the same VM, everything worked.

I was wondering why, so I did a diff on the ~/.kube dir between Minikube and MicroK8s and the only real difference was that .kube/config had a different IP address for clusters -> cluster -> server (172.x.x.x for Minikube, 127.0.0.1 for MicroK8s).
In the gluu install dir, the difference was that the gluu_minikube/settings.json file had a different IP address and the APP_VOLUME_TYPE variable was set to 1 and 2, resp. All other differences were just timestamps, different autogenerated passwords, etc.

This is not a big problem for me, but I'm sharing it because it looks to me like it might be a bug.

OS: Ubuntu 18.04

**Comment by moabu** [comment]
yes its because you most likely set the wrong IP for Minikube or a config issue in Minikube occurred because of an invalid installation. Please attempt to grab the ip using `minikube ip`. 
Closing this issue as it has  not been replicated in same environment.

**Comment by hhblnw** [comment]
The problem turned out to be an old /data directory from a previous install. When I deleted /data and re-installed gluu, everything worked.

As a suggestion, I think `pygluu-kubernetes-linux.pyz uninstall` should delete `/data/jackrabbit` and `/data/opendj`, or the fact that gluu keeps stuff in /data should be documented.

**Comment by moabu** [comment]
> As a suggestion, I think pygluu-kubernetes-linux.pyz uninstall should delete /data/jackrabbit and /data/opendj, or the fact that gluu keeps stuff in /data should be documented.

Yes it should be documented but not deleted as that's an irreversible action the user most likely will not want if any work has been done on the demo installation. 

Thanks for your suggestion.

**Comment by nynymike** [comment]
We don't provide support on the Gluufederaton Github. We don't even offer community support on kubernetes on the [Public Gluu forums](https://support.gluu.org). If you want cloud native community support on a distribution of our open source software, you'll have to move to the [Janssen Project](https://jans.io), where there are several support channels. While Gluu 4.x is free and open source, Gluu engineers have a limited scope for the types of questions we'll answer.

**Comment by PhilParisot** [comment]
Right, and you felt you needed to respond?

True answer is Gluu depends on monetizing support as its main revenue, but you shouldn't block @moabu or @hhblnw from helping me out if they decide to, all I did was ask, they are free to ignore and not respond.

I'm well away there is no free/unpaid community support, but I am surprised you will spend time and money cracking down on folks asking for help.

**Comment by nynymike** [comment]
I'm not cracking down, I'm telling you that if you want community engagment, you need to use the head of the project. That is not atypical for other projects.
