### ISSUE TITLE
Add detail check on settings.json before loading.

### ISSUE THREAD

**Issue by moabu** [GluuFederation/cloud-native-edition#164]
**Is your feature request related to a problem? Please describe.**

It is possible to manually edit `settings.json` which is used to hold installation settings.

**Describe the solution you'd like**

Add a detail check per setting comparing it with the valid options for each setting.

**Comment by rizarsyi** [comment]
Hi I will be working on this issue, Is there any standard valid options for each setting?

**Comment by moabu** [comment]
Yes. You can deduce that from following the settings. Forexample, you have a set of vars that can only be `Y` or `N` any other option is immediately invalid. You need to break settings into chunks . Passwords and hence must meet the password requirements, strings that cannot have numbers so alphanumrical , strings that can only be `Y` or `N`, only numbers, `false` and `true`, any string, strings set to specific options like `AWS_LB_TYPE` which can only be  "", "clb", "nlb" or "alb". 
https://www.gluu.org/docs/gluu-server/4.2/installation-guide/install-kubernetes/#settingsjson-parameters-file-contents
Look over the prompts for each variable.

**Comment by rizarsyi** [comment]
hi @moabu this `VERIFY_EXT_IP` variable were not used? this has "Y" or "N" on the docs

**Comment by moabu** [comment]
Its used to verify the ip if placed manually. It is a `Y` or `N`
