### ISSUE TITLE
Selecting upgrade version overwrites custom images 

### ISSUE THREAD

**Issue by iromli** [GluuFederation/cloud-native-edition#223]
When user selects upgrade version, the custom images are reverted to the ones defined in `gluu_versions.json`.

**Steps to reproduce**

1. Given custom image in `settings.json`

    ```
   "LDAP_IMAGE_NAME": "iromli/opendj"
    ```
1. Go to `Utilities > Upgrade` and follow the wizards
1. The wizard at `/gluu-upgrade` will ask for upgrade version; choose one
1. Summary settings shows that `LDAP_IMAGE_NAME` is reverted to default `gluufederation/opendj`

**Expected behavior**

Any custom image name and/or tag should be left intact regardless of selected upgrade version

**Comment by rizarsyi** [comment]
@iromli do you want me to fix this on terminal too?

**Comment by rizarsyi** [comment]
@moabu i'm using same code with terminal https://github.com/GluuFederation/cloud-native-edition/blob/f60b974416b59e4fb689bfd9e2977d3a99a639b4/pygluu/kubernetes/terminal/upgrade.py#L37

**Comment by iromli** [comment]
@rizarsyi  @moabu The custom image tag still overwritten. Custom image name is left intact.

**Comment by rizarsyi** [comment]
ok, I'm still working on reordering the wizard steps for upgrade feature
