### ISSUE TITLE
IP to access cloud-native-installer cannot be found in Gluu server

### ISSUE THREAD

**Issue by dannyboydsilva** [GluuFederation/cloud-native-edition#241]
I've tried installing Gluu using Minikube through the GUI-Alpha. However, step 3 mentions to enter in the IP address. I've got the minikube as well as Load Balancer IP( Baremetal using Metallb) as well as the port. However, I've tried to punch in all possible IP and port. It doesn't seem to work.

**Comment by moabu** [comment]
The GUI will attempt to grab the ip itself. Only if it fails will it instruct you to place an ip. You cannot place `ports` that doesn't make much sense. Did you try to place the output of `minikube ip` command ?

**Comment by dannyboydsilva** [comment]
> The GUI will attempt to grab the ip itself. Only if it fails will it instruct you to place an ip. You cannot place `ports` that doesn't make much sense. Did you try to place the output of `minikube ip` command ?

Hi, yes, I did try that too. I've tried a load balancer, a node port, minikube IP but nothing seemed to work

**Comment by moabu** [comment]
Can you clarify on the issue / error you see please. An image or error message would help.

**Comment by dannyboydsilva** [comment]
> Can you clarify on the issue / error you see please. An image or error message would help.

https://ibb.co/zF69Y99

This is the load balancer IP I have received. However, when I go to punch it in my browser, I get a time out. I've switched from Minikube to Kubernetes today.

**Comment by moabu** [comment]
This issue is not replicable on Minikube. We do not claim to support bare metal with Metallb as Metallb is immature and in beta phase.

Minikube ip was automatically detected and was = to `minikube ip`. 

Please try a pure minikube installation.

**Comment by moabu** [comment]
Your issue is likely not related to Gluu installation but the infrastructure.
