### ISSUE TITLE
GUI Installer job under Kubernetes

### ISSUE THREAD

**Issue by dannyboydsilva** [GluuFederation/cloud-native-edition#242]
The GUI Installer job script given on the website 

cat <<EOF | kubectl apply -f -
apiVersion: apps/v1
kind: Job

should be

cat <<EOF | kubectl apply -f -
apiVersion: batch/v1
kind: Job

since terminal gives the following error
error: unable to recognize "STDIN": no matches for kind "Job" in version "apps/v1"

**Comment by moabu** [comment]
That depends on the kubernetes version you are using. Nevertheless, it has been changed to assume the latest.
