### ISSUE TITLE
GUI-Alpha Kubernetes Installation does not work

### ISSUE THREAD

**Issue by dannyboydsilva** [GluuFederation/cloud-native-edition#243]
I have tried all possible ways to install from the load balancer IP but the webpage times out every single time. Please try and fix this since Keycloak has a stable Kubernetes deployment but Gluu still lacks one. Thanks

**Comment by dannyboydsilva** [comment]
Bug: Installer does not load. IP times out.

**Comment by moabu** [comment]
Your bug report is not following any report standards. You need to be clear about your report. Most importantly, the GUI is alpha version which means it's not meant to be used to install production systems. We have  stable pathways for installing Gluu on Kuberenets and all are currently being used by several customers.

Please refer to our docs : https://gluu.org/docs

The stable version of the GUI will be out in Gluu 5.0, so at the moment please use our stable pathways and open a bug report with detailed information as the template walks you through that . Skipping that does not help at all. The pathways that the GUI installer uses have been tested and are recurringly tested per commit , making a claim needs evidence and a path of reporducing it so we can address and fix .

Please open an issue with more information.
Thanks
