### ISSUE TITLE
Missing pygluu-kubernetes-osx.pyz after v1.2.2

### ISSUE THREAD

**Issue by mookkiah** [GluuFederation/cloud-native-edition#262]
**Describe the bug**

I see the osx flavor of pygluu-kubernetes stopped getting into artifacts since v1.2.3.

**To Reproduce**
See release artifact of v1.2.2 and v1.2.3

**Expected behavior**
Option
-  have pygluu-kubernetes-osx.pyz in all releases
- Explain the release notes/changelog why it is disappeared and how to manage the change if we used it.

**Screenshots**
![image](https://user-images.githubusercontent.com/8975264/100122815-d4a3ea80-2e47-11eb-9c6c-78a1829f4c55.png)
![image](https://user-images.githubusercontent.com/8975264/100122871-eb4a4180-2e47-11eb-8aec-ee0146fa35e0.png)

**Additional context**
After looking little deeper, I noticed [github release workflow]( https://github.com/GluuFederation/cloud-native-edition/commits/master/.github/workflows/release.yml) introduced when 1.2.2 

Please shed some light around this area so that we can aware how to transition to new releases

**Comment by iromli** [comment]
@mookkiah have you tried building the `.pyz` manually? https://github.com/GluuFederation/cloud-native-edition#python-zipapp

**Comment by moabu** [comment]
@mookkiah you can build it manually for osx following instructions on our main page. We have had issues with osx package distribution and have removed it for that reason. The user has options such as using pip install or simply make after cloning the repo.
