### ISSUE TITLE
Replica counts not being honored for helm installations

### ISSUE THREAD

**Issue by shairozan** [GluuFederation/cloud-native-edition#268]
**Describe the bug**
After generating a settings.json file that contains replica counts greater than one:

```json
  "OXAUTH_REPLICAS": 2,
  "OXTRUST_REPLICAS": 2,
  "LDAP_REPLICAS": 3,
  "OXSHIBBOLETH_REPLICAS": 2,
  "OXPASSPORT_REPLICAS": 2,
  "OXD_SERVER_REPLICAS": 2,
```

running `pygluu-kubernetes.pgz helm-install` will install gluu as desired _without_ the correct replica counts. The only stateful set that was scaled up was openDJ. I had to manually scale the other services and verify functionality

**To Reproduce**
1. `pygluu-kubernetes.pgz generate-settings`
2. Input replica counts greater than 1
3. `pygluu-kubernetes.pgz helm-install`
4. Verify statefulset count and pod count with `kubectl`

**Expected behavior**
If settings.json was built to request 2 replicas of everything, or 3 of everything, I would expect the stateful sets to already be scaled for it

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS 10.15.7
 - Browser chrome 
 - Version 87

**Additional context**
The version of pygluu I'm working with is built from source from the last tag with the zipapp method. Also it feels like it would be worth adding a `version` subcommand for support purposes

**Comment by moabu** [comment]
Thanks @shairozan for reporting this issue. We will check it out.
