### ISSUE TITLE
ldap backup schedule is hardcoded. It should use the configured value.

### ISSUE THREAD

**Issue by mookkiah** [GluuFederation/cloud-native-edition#281]
Even though the ldap backup schedule is configurable in settings.json

```
  "LDAP_BACKUP_SCHEDULE": "*/30 * * * *",
```

It is hardcoded in the [cronjob](https://github.com/GluuFederation/cloud-native-edition/blob/c300c5bf138317fc689b8a8e8e5229083e81fc4e/pygluu/kubernetes/templates/helm/ldap-backup/templates/cronjobs.yaml#L8)

**Comment by moabu** [comment]
https://github.com/GluuFederation/cloud-native-edition/commit/51276626decd9555f80b0d9cd4f6b1f9a716e323
