### ISSUE TITLE
Failed to install to K8s 1.6.15-eks

### ISSUE THREAD

**Issue by ledohoanglong** [GluuFederation/cloud-native-edition#305]
Hi Gluu team,

My team tried deploying Gluu in our k8s clusters. However, we met the following error when installing ningress-ingress-nginx-controller:

_ERROR - Error: chart requires kubeVersion: >=v1.17.0-0 which is incompatible with Kubernetes v1.16.15-eks-ad4801_

In our case, upgrading k8s isn't an option right now. Is there anyway we can work around this issue?

**Comment by moabu** [comment]
Hi @ledohoanglong , 

1. Please use branch 4.2, not master.

2. Support for cloud-native installations requires a support plan. Please open a ticket at support.gluu.org. 

3. The latest has a dev chart that does work with 1.16. But we will no longer support 1.16 very soon. Use helm to install and you should be fine.
 
```
gluu/gluu       1.4.4-a         4.2.3           Gluu Access and Identity Mangement
```

```
helm repo add gluu https://gluufederation.github.io/cloud-native-edition/pygluu/kubernetes/templates/helm
helm repo update
helm install <release-name> gluu/gluu -n <namespace> -f overide-values.yaml
```
