### ISSUE TITLE
ldab-backup image name is invalid in Helm chart release 4.3.0

### ISSUE THREAD

**Issue by MohamedGadMidships** [GluuFederation/cloud-native-edition#338]
**Describe the bug**

The Helm chart has invalid image name 
https://github.com/GluuFederation/cloud-native-edition/blob/4.3/pygluu/kubernetes/templates/helm/ldap-backup/values.yaml

**To Reproduce**
1. Install Gluu using helm release 4.3.0
2. Run $ kubectl -n gluu get po
3. See result
NAME                                READY   STATUS             RESTARTS   AGE
gluu-jackrabbit-first-0             1/1     Running            0          107m
gluu-ldap-backup-1625101200-vpp6r   0/1     ImagePullBackOff   0          107m
gluu-opendj-0                       1/1     Running            0          107m
gluu-oxauth-894d57846-596c6         1/1     Running            0          107m
gluu-oxtrust-0                      1/1     Running            1          107m

3. Run $ kubectl -n gluu describe pod gluu-ldap-backup-1625101200-vpp6r

Events:
  Type     Reason   Age                   From     Message
  ----     ------   ----                  ----     -------
  Normal   BackOff  6m3s (x281 over 70m)  kubelet  Back-off pulling image "gluufederation/opendj:4.3.0_01"
  Warning  Failed   61s (x304 over 70m)   kubelet  Error: ImagePullBackOff

**Expected behavior**
All Gluu pods should be in Running state

**Root Cause**
The following image is not available:
gluufederation/opendj:4.3.0_01

The following image is available:
gluufederation/opendj:4.3.0_b1

**Comment by moabu** [comment]
Yes that should be b1

**Comment by moabu** [comment]
we will submit a fix soon

**Comment by moabu** [comment]
https://github.com/GluuFederation/cloud-native-edition/releases/tag/v1.6.2 assets.
