### ISSUE TITLE
helm chart usable with gitops

### ISSUE THREAD

**Issue by hobyte** [GluuFederation/cloud-native-edition#387]
**Is your feature request related to a problem? Please describe.**
I want to try out gluu on a baremetal server. As I'm currently using argocd to manage my clusters, installung gluu with pygluu isn't a really a option, because it needs manuell input.

**Describe the solution you'd like**
The best would be to have a single helm chart to install gluu, but any way to make installation of gluu with gitops tolls would be nice

**Describe alternatives you've considered**
I've tried to install gluu like discribed in the [docs](https://gluu.org/docs/gluu-server/installation-guide/install-kubernetes/#installing-gluu-using-helm-manually), but I can't get wich helm chart I need to install in the last step

**Comment by nynymike** [comment]
You'll need to register on https://support.gluu.org and post your question there. Although, cloud native questions are not supported in the community either. You may want to contact [Gluu sales](https://gluu.org/contact-us/) to discuss commercial support options, or understand how Gluu supports pre-sales opportunities.

**Comment by makeaweli** [comment]
+1 ArgoCD/Flux is super common.
