### ISSUE TITLE
cr-rotate: google credentials not being mounted with spanner selection

### ISSUE THREAD

**Issue by gustavovalverde** [GluuFederation/cloud-native-edition#413]
**Describe the bug**
Helm templates for cr-rotate does not have a condition to mount google credentials when using Cloud Spanner, which leaves the deployment unusable when this option is selected:

https://github.com/GluuFederation/cloud-native-edition/blob/4.3/pygluu/kubernetes/templates/helm/gluu/charts/cr-rotate/templates/daemonset.yaml#L61-L69

**To Reproduce**
1. Install with `./pygluu-kubernetes.pyz helm-install`
2. Select Cloud Spanner as an option
3. cr-rotate pods gets into a crashing loop

**Expected behavior**
Get the `google-sa` volume mounted

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**

**Comment by moabu** [comment]
Checking ...
