### ISSUE TITLE
Most of the gluefederation repositories have been removed from Docker Hub

### ISSUE THREAD

**Issue by TTmaister** [GluuFederation/cloud-native-edition#558]
**Describe the bug**
Can't find repositories oxauth, oxshibboleth, oxtrust, oxpassport ... from docker hub

**To Reproduce**
https://hub.docker.com/search?q=gluufederation

**Screenshots**
![image](https://github.com/GluuFederation/cloud-native-edition/assets/25279650/9dbc350c-d0f7-4d62-b1d5-3db9dad43a6b)

**Comment by emilhdiaz** [comment]
The version chart also shows the exact same release date and EOL date for the CE editions for versions 4.3.x and 4.4.x (see here: https://gluu.org/docs/). Is that meant to mean that those versions are/were completely unsupported??

**Comment by moabu** [comment]
Hey @TTmaister ,

I'm sorry you ran into troubles. We have made an announcement in regards of this issue.  Please read carefully the following and head to the upstream [Janssen projec](https://github.com/JanssenProject/jans )t which contains about all you want!
 
<img width="348" alt="Screenshot 2023-06-20 at 5 47 32 PM" src="https://github.com/GluuFederation/cloud-native-edition/assets/47318409/64d66933-da49-4fc1-87ca-f4882d96e94e">
